### ISSUE TITLE
chore: create a proper readme

### ISSUE THREAD

**Issue by tony-go** [NabilSli/projet2#10]

**Comment by NabilSli** [comment]
Done ! what do you think?

**Comment by tony-go** [comment]
You didn't raise a PR 😨 😅 ?

A few thoughts:
- The final output (the Netlify link) should be at the top of the README
- "PROJECT 2 of OpenClassroom's Web developer Course" -> Write something more personal like: "This website is my first achievement as a web developer. I did it during my boot camp _OpenClassroom's Web developer_" - You can tweak the sentence as you like.
- html -> `HTML` 
- Css -> `CSS`
- Git and GitHub -> `GIT`
- Feel free to use more icons like we did here: https://github.com/tony-go/clix or here: https://github.com/restqa/restqa (keep these ones as reference for the future)

🙏🏼  Please raise a PR for these changes then we can discuss more there.

With love 😍

**Comment by NabilSli** [comment]
job done !
